# Generated by Django 4.2.6 on 2023-10-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nyilvantartas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vezetek_nev', models.CharField(max_length=30)),
                ('kereszt_nev', models.CharField(max_length=30)),
                ('kulcs_szama', models.CharField(max_length=5)),
                ('datum', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
