# Generated by Django 4.2.6 on 2023-10-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kezdolap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nyilvantartas',
            name='kulcs_szama',
            field=models.CharField(max_length=10),
        ),
    ]
