# Generated by Django 4.2.6 on 2023-10-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kezdolap', '0002_alter_nyilvantartas_kulcs_szama'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nyilvantartas',
            old_name='kulcs_szama',
            new_name='kulcs_szam',
        ),
        migrations.AddField(
            model_name='nyilvantartas',
            name='visszaadva',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
