# Generated by Django 4.2.6 on 2023-10-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kezdolap', '0003_rename_kulcs_szama_nyilvantartas_kulcs_szam_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nyilvantartas',
            name='kulcs_szam',
            field=models.CharField(max_length=15),
        ),
    ]
