# Generated by Django 4.2.6 on 2023-10-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kezdolap', '0004_alter_nyilvantartas_kulcs_szam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kulcs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=100, unique=True)),
                ('mennyiseg', models.IntegerField(default=0)),
                ('max_mennyiseg', models.IntegerField(default=100)),
            ],
        ),
    ]
