# Generated by Django 4.2.6 on 2023-10-16 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kezdolap', '0006_rename_nev_kulcs_kulcs_szam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kulcs',
            old_name='kulcs_szam',
            new_name='nev',
        ),
    ]
